# pyproject.toml
# target-version = "py313"

[tool.black]
target-version = ["py311", "py312", "py313"]

[tool.isort]
profile = "black"

[tool.ruff]
# Enable Pyflakes `E` and `F` codes by default.
select = ["E", "F"]
ignore = ["E501", "E741"]
